#ifndef CHOWDER_ANVIL_ERR_H
#define CHOWDER_ANVIL_ERR_H

enum anvil_err {
	ANVIL_OK,
	ANVIL_CHUNK_MISSING,
	ANVIL_READ_ERROR,
	ANVIL_ZLIB_ERROR,
	ANVIL_BAD_NBT,
	ANVIL_BAD_CHUNK,
	ANVIL_BAD_DATA_VERSION,
	ANVIL_BAD_RANGE, /* chunk range spans more than one region */
	ANVIL_NO_MEMORY,
	ANVIL_ERRNO,
};

#endif // CHOWDER_ANVIL_ERR_H
